name: ezycourse
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # carousel_slider: ^4.2.1
  chewie: ^1.8.1
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  dotted_border: ^2.1.0
  dropdown_search: ^5.0.6
  easy_draggable: ^0.0.2
  emoji_picker_flutter: ^2.2.0
  cached_network_image: ^3.3.0
  expandable_text: ^2.3.0
  file_picker: ^5.2.0
  # flutter:
  #   sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_holo_date_picker: ^1.1.3
  flutter_rating_bar: ^4.0.1
  flutter_reaction_button: ^3.0.0+3
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.10+1
  get: 4.6.6
  get_storage: ^2.1.1
  http_parser: ^4.0.2
  image_cropper: ^8.0.1
  image_picker: ^1.0.7
  interactive_viewer_2: ^0.0.10
  intl: ^0.19.0
  newsfeed_multiple_imageview: ^1.0.1
  path_provider: ^2.1.3
  photo_manager: ^3.0.0
  reaction_button: ^0.0.7
  readmore: ^3.0.0
  screenshot: ^3.0.0
  share_plus: ^9.0.0
  shimmer: ^3.0.0
  story: ^1.1.0
  url_launcher: ^6.2.6
  video_player: ^2.9.2
  # video_thumbnail: ^0.5.3
  visibility_detector: ^0.4.0+2
  flutter_stripe: ^11.1.0
  flutter_widget_from_html: ^0.15.2
  flutter_html: ^3.0.0-beta.2
  
  # dropdown_plus: ^0.0.9
  # drop_down_list: ^0.0.8
  flutter_multiselect: ^1.0.0
  permission_handler: ^11.3.1
  intl_phone_number_input: ^0.7.4
  flutter_otp_text_field: ^1.2.0
dependency_overrides:
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: SfProDisplay
      fonts:
        - asset: fonts/SfProDisplay-Regular.otf
          weight: 500
        - asset: fonts/SfProDisplay-Medium.otf
          weight: 600
        - asset: fonts/SfProDisplay-Bold.otf
          weight: 700
    - family: CedarvilleCursive
      fonts:
        - asset: fonts/CedarvilleCursive-Regular.ttf
    - family: CourierPrime
      fonts:
        - asset: fonts/CourierPrime-Regular.ttf
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-VariableFont_wght.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Medium.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: WorkSans
      fonts:
        - asset: fonts/WorkSans-VariableFont_wght.ttf

  assets:
    - assets/logo/
    - assets/image/
    - assets/icon/
    - assets/icon/appbar/
    - assets/icon/navbar/
    - assets/icon/reaction/
    - assets/icon/create_post/
    - assets/icon/user_profile/
    - assets/icon/user_menu/
    - assets/icon/post_action/
    - assets/icon/comment/
    - assets/icon/group_profile/
    - assets/other/
    - assets/icon/live_event/
    - assets/icon/other_profile/
    - assets/image/story_bg/
    - assets/icon/group_file_icons/
    - assets/icon/notification/
    - assets/icon/wallet/
    - assets/icon/seller_panel/
    - assets/icon/buyer_panel/
    - assets/icon/marketplace/
    - assets/icon/settings/
